"""index files by chat and album

Revision ID: fa1e753723f8
Revises: cd0c79bcf30a
Create Date: 2026-09-22 10:24:21.405429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa1e753723f8'
down_revision: Union[str, Sequence[str], None] = 'cd0c79bcf30a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index('ix_files_chat_grouped', ['chat_id', 'grouped_id'], unique=False)

    # ### end Alembic commands ###
    # Without fresh statistics SQLite keeps using the (chat_id, message_id) unique index for
    # album lookups and the caption fill stays a full scan of the chat.
    op.execute("ANALYZE")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index('ix_files_chat_grouped')

    # ### end Alembic commands ###
